
export const comments = [
	{
		postID: 1,
		email: 'brentjett@gmail.com',
		date: '2018-05-12',
		content: 'What a great post! I hope all the comments are as positive as mine!',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 2,
		email: 'bob@superhonestwebplace.com',
		date: '2018-05-12',
		content: 'Aenean lacinia bibendum nulla sed consectetur. Donec id elit non mi porta gravida at eget metus. Donec sed odio dui.',
		isSpam: true,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 3,
		email: 'ben.dover@snarkyweb.com',
		date: '2018-05-12',
		content: 'What a great post! I hope all the comments are as positive as mine!',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 4,
		email: 'hugh.jass@dannysmells.biz',
		date: '2018-10-03',
		content: 'Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Nulla vitae elit libero, a pharetra augue. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec ullamcorper nulla non metus auctor fringilla.',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 5,
		email: 'jerk@anonymousjerk.com',
		date: '2019-02-08',
		content: 'You thought this should be on the web?',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 11,
		email: 'brentjett@gmail.com',
		date: '2018-05-12',
		content: 'What a great post! I hope all the comments are as positive as mine!',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 21,
		email: 'bob@superhonestwebplace.com',
		date: '2018-05-12',
		content: 'Aenean lacinia bibendum nulla sed consectetur. Donec id elit non mi porta gravida at eget metus. Donec sed odio dui.',
		isSpam: true,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 31,
		email: 'ben.dover@snarkyweb.com',
		date: '2018-05-12',
		content: 'What a great post! I hope all the comments are as positive as mine!',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 41,
		email: 'hugh.jass@dannysmells.biz',
		date: '2018-10-03',
		content: 'Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Nulla vitae elit libero, a pharetra augue. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec ullamcorper nulla non metus auctor fringilla.',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 51,
		email: 'jerk@anonymousjerk.com',
		date: '2019-02-08',
		content: 'You thought this should be on the web?',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 12,
		email: 'brentjett@gmail.com',
		date: '2018-05-12',
		content: 'What a great post! I hope all the comments are as positive as mine!',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 22,
		email: 'bob@superhonestwebplace.com',
		date: '2018-05-12',
		content: 'Aenean lacinia bibendum nulla sed consectetur. Donec id elit non mi porta gravida at eget metus. Donec sed odio dui.',
		isSpam: true,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 32,
		email: 'ben.dover@snarkyweb.com',
		date: '2018-05-12',
		content: 'What a great post! I hope all the comments are as positive as mine!',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 42,
		email: 'hugh.jass@dannysmells.biz',
		date: '2018-10-03',
		content: 'Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Nulla vitae elit libero, a pharetra augue. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec ullamcorper nulla non metus auctor fringilla.',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 52,
		email: 'jerk@anonymousjerk.com',
		date: '2019-02-08',
		content: 'You thought this should be on the web?',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 13,
		email: 'brentjett@gmail.com',
		date: '2018-05-12',
		content: 'What a great post! I hope all the comments are as positive as mine!',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 23,
		email: 'bob@superhonestwebplace.com',
		date: '2018-05-12',
		content: 'Aenean lacinia bibendum nulla sed consectetur. Donec id elit non mi porta gravida at eget metus. Donec sed odio dui.',
		isSpam: true,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 33,
		email: 'ben.dover@snarkyweb.com',
		date: '2018-05-12',
		content: 'What a great post! I hope all the comments are as positive as mine!',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 43,
		email: 'hugh.jass@dannysmells.biz',
		date: '2018-10-03',
		content: 'Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Nulla vitae elit libero, a pharetra augue. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec ullamcorper nulla non metus auctor fringilla.',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
	{
		postID: 53,
		email: 'jerk@anonymousjerk.com',
		date: '2019-02-08',
		content: 'You thought this should be on the web?',
		isSpam: false,
		isApproved: true,
		thumbnail: 'https://secure.gravatar.com/avatar/8f731fcc495fd2c20eb79ec8dead0a5f?s=64&d=mm&r=g',
	},
]

export const updates = [
	{

	},
]
